# This is a basic workflow to help you get started with Actions

name: BackendDeploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "test/seunmgmin" ]
    paths:
      - 'back/**'
  pull_request:
    branches: [ "test/seunmgmin" ]
    paths:
      - 'back/**'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./back
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
        
      - name: ls command
        run: ls 
        working-directory: ${{ env.working-directory }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ${{ env.working-directory }}

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir -p deploy
        working-directory: ${{ env.working-directory }}
        
      # Jar 파일 Copy
      
      - name: Copy Jar
        run: zip -r back *
        working-directory: ${{ env.working-directory }}
      - name: Copy Jar
        run: cp ./back.zip ./deploy/
        working-directory: ${{ env.working-directory }}
      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
        run: aws s3 cp --region ap-northeast-2 --acl private ./deploy/back.zip s3://pickmovie-back-bucket/
        working-directory: ${{ env.working-directory }}
        
